#ifndef PROTOCOL_CONFIG_H
#define PROTOCOL_CONFIG_H

constexpr int DRAGON_ARENA_PROTOCOL_VERSION = 2;
constexpr int DRAGON_ARENA_TICK_INTERVAL_MS = 50;
constexpr int DRAGON_ARENA_SNAPSHOT_INTERVAL_MS = 250;

#endif
